# settings for domain of waveforms
domain_settings:
  name: UniformFrequencyDomain
  kwargs:
    f_min: 10.0
    f_max: 1024.0
    delta_f: 0.125  # Expressions like 1.0/8.0 would require eval and are not supported
    window_factor: 1.0 # This should maybe be in noise settings? It is not used for the generation of waveform polarizations

# settings for waveform generator
waveform_generator_settings:
  approximant: IMRPhenomPv2 # SEOBNRv4PHM
  f_ref: 20.0

# settings for intrinsic prior over parameters
intrinsic_prior:
  # prior for non-fixed parameters
  mass_1: bilby.core.prior.Constraint(minimum=10.0, maximum=80.0)
  mass_2: bilby.core.prior.Constraint(minimum=10.0, maximum=80.0)
  mass_ratio: bilby.core.prior.Uniform(minimum=0.125, maximum=1.0)
  chirp_mass: bilby.core.prior.Uniform(minimum=25.0, maximum=100.0)
  phase: default
  a_1: bilby.core.prior.Uniform(minimum=0.0, maximum=0.88)
  a_2: bilby.core.prior.Uniform(minimum=0.0, maximum=0.88)
  tilt_1: default
  tilt_2: default
  phi_12: default
  phi_jl: default
  theta_jn: default
  # reference values for fixed (extrinsic) parameters
  luminosity_distance: 100.0 # Mpc
  t_geocent: 0.0 # s

reference_frequency: 20.0  # Hz

waveform_dataset_generation_settings:
  # Number of waveforms to generate for building the SVD basis
  num_wfs_basis: 10000
  # Number of waveforms to generate for the waveform dataset
  num_wfs_dataset: 50000
  # Truncate the SVD basis at this size. No truncation if zero.
  rb_max: 500
